packages:
  - apps/*
  - libs/*
  - docs/*

catalog:
  '@eslint/eslintrc': ~3.3
  '@mocks-server/main': ~4.1
  '@nestjs/cli': ~11.0.0
  '@nestjs/common': ~11.0.1
  '@nestjs/core': ~11.0.1
  '@nestjs/event-emitter': ~3.0.1
  '@nestjs/platform-express': ~11.0.1
  '@nestjs/schematics': ~11.0.0
  '@nestjs/testing': ~11.0.1
  '@nestjs/typeorm': ~11.0.0
  '@next/env': ~15.5
  '@tailwindcss/postcss': ~4.1
  '@testing-library/jest-dom': ~6.8.0
  '@testing-library/react': ~16.3.0
  '@types/express': ~5.0.0
  '@types/jest': ~30.0
  '@types/node': 24.3.3
  '@types/react': 19.1.17
  '@types/react-dom': ~19.1
  '@types/supertest': ~6.0.2
  autoprefixer: ~10.4
  axios: ~1.4.0
  better-sqlite3: ~12.6.2
  class-transformer: ~0.5.1
  class-validator: ~0.14.0
  connect-livereload: ~0.6
  dotenv: ~16.3
  eslint: ~9.34
  eslint-config-next: ~15.5
  eslint-config-prettier: ~10.1.0
  eslint-plugin-prettier: ~5.2.2
  eventemitter2: ~7.4
  express: ~5.1
  generate-react-cli: ~8.4.9
  jest: ~30.1
  jest-environment-jsdom: ~30.1
  livereload: ~0.10
  motion: ~12.23.28
  mysql2: ~3.3
  next: ~15.5.9
  nodemon: ~3.1
  postcss: ~8.5
  postcss-cli: ~11.0
  prettier: ~3.4.2
  react: ~19.1
  react-dom: ~19.1
  reflect-metadata: ~0.2.2
  rxjs: ~7.8.1
  source-map-support: ~0.5.21
  sqlite3: ~5.1
  supertest: ~7.0.0
  swagger-ui-express: ~5.0
  tailwindcss: ~4.1
  ts-jest: ~29.4
  ts-loader: ~9.5.2
  ts-node: ~10.9.2
  tsconfig-paths: ~4.2.0
  typeorm: ~0.3.17
  typescript: ~5.9.3
  yamljs: ~0.3

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - better-sqlite3
  - unrs-resolver

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp